// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewGroupPost struct {
	Description string   `json:"Description"`
	ImageURL    []string `json:"ImageURL"`
	Visibility  string   `json:"Visibility"`
	GroupID     string   `json:"GroupID"`
}

type NewPost struct {
	Description string   `json:"Description"`
	ImageURL    []string `json:"ImageURL"`
	Visibility  string   `json:"Visibility"`
}

type NewUser struct {
	Name     string    `json:"Name"`
	Surname  string    `json:"Surname"`
	Email    string    `json:"Email"`
	Dob      time.Time `json:"DOB"`
	Gender   string    `json:"Gender"`
	Password string    `json:"Password"`
}

type InputLogin struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}
